JLTMEntProj/Controllers/ManageProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JLTMEntProj.Models;

namespace JLTMEntProj.Controllers
{
    [Authorize (Roles ="canEdit")]
    public class ManageProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Products
        public ActionResult Index(string sortOrder, string searchString)
        {
           
            var products = from p in db.Products
                           select p;

            if (!String.IsNullOrEmpty(searchString))
            {
                products = db.Products.Where(p => p.Name.Contains(searchString)
                                       || p.Description.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name":
                    products = products.OrderBy(p => p.Name);
                    break;
                case "desc":
                    products = products.OrderBy(p => p.Description);
                    break;
                case "quan":
                    products = products.OrderBy(p => p.Quantity);
                    break;
                case "price":
                    products = products.OrderBy(p => p.Price);
                    break;
                default:
                    products = products.OrderBy(p => p.Name);
                    break;
            }


            return View(products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        [Authorize(Roles = "canEdit")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "canEdit")]
        public ActionResult Create([Bind(Include = "ProductId,Name,Description,Quantity,Price")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Products/Edit/5
        [Authorize(Roles = "canEdit")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "canEdit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductId,Name,Description,Quantity,Price")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Products/Delete/5
        [Authorize(Roles = "canEdit")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "canEdit")]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JLTMEntProj/Controllers/ShoppingController.cs
using JLTMEntProj.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JLTMEntProj.Controllers
{
    /// <summary>
    /// Controller for the shopping of the web
    /// </summary>
    /// <author>Tuan Mai</author>

    public class ShoppingController : Controller
    {
        // Declare Constant for shopping cart obj
        private const string SHOPPING_CART_SESSION_OBJ = "ShoppingCart";

        private ApplicationDbContext db = new ApplicationDbContext();

        /// <summary>
        /// Getter for the shopping cart via session of shopping cart object
        /// </summary>
        public ShoppingCart ShoppingCart
        {
            get
            {
                ShoppingCart cart = Session[SHOPPING_CART_SESSION_OBJ] as ShoppingCart;

                if (cart == null)
                {   // Set new session to shopping cart object
                    cart = new ShoppingCart();
                    Session[SHOPPING_CART_SESSION_OBJ] = cart;
                }

                return cart;
            }
        }

        /// <summary>
        /// Shop ActionResult to display all the products in the shop
        /// Sorting functionality
        /// </summary>
        /// <returns>Returns View</returns>
        public ActionResult Shop(string sortOrder, string searchString)
        {
            var products = from p in db.Products
                           select p;

            if (!String.IsNullOrEmpty(searchString))
            {   // Search through products
                products = db.Products.Where(p => p.Name.Contains(searchString)
                                       || p.Description.Contains(searchString));
            }

            switch (sortOrder)
            {   // The sort order
                case "name":
                    products = products.OrderBy(p => p.Name);
                    break;
                case "desc":
                    products = products.OrderBy(p => p.Description);
                    break;
                case "quan":
                    products = products.OrderBy(p => p.Quantity);
                    break;
                case "price":
                    products = products.OrderBy(p => p.Price);
                    break;
                default:
                    products = products.OrderBy(p => p.Name);
                    break;
            }

            return View(products.ToList());
        }

        /// <summary>
        /// ViewCart ActionResult to display the list of items in the shopping cart
        /// </summary>
        /// <returns View(ShoppingCart)></returns>
        public ActionResult ViewCart()
        {
            return View(ShoppingCart);
        }

        /// <summary>
        /// AddToCart ActionResult to add the product to the user's shopping cart
        /// </summary>
        /// <param name="productId"></param>
        /// <returns>RedirectsToAction</returns>>
        public ActionResult AddToCart(int productId)
        {
            // Search the database for product with same id
            Product product = db.Products.Find(productId);

            if (product != null)
            {
                ShoppingCart.AddProduct(product, 1);    // Call method to add this product to shopping cart
            }

            return RedirectToAction("ViewCart");
        }

        /// <summary>
        /// RemoveFromCart ActionResult to remove the product from the shopping cart that user selected
        /// </summary>
        /// <param name="productId"></param>
        /// <returns>Returns View</returns>
        public ActionResult RemoveFromCart(int productId)
        {
            ShoppingCart.RemoveProduct(productId, 1);

            return View("ViewCart", ShoppingCart);
        }

        /// <summary>
        /// ProceedToCheckout ActionResult to handle the Checkout view
        /// </summary>
        /// <returns>Returns View</returns>
        public ActionResult ProceedToCheckout()
        {
            return View("CheckoutView", ShoppingCart);
        }

        /// <summary>
        /// PaymentOptions ActionResult to display view for users to pay
        /// </summary>
        /// <returns>Returns View</returns>
        public ActionResult PaymentOptions()
        {
            return View("Pay", ShoppingCart);
        }

        /// <summary>
        /// Paid ActionResult calls UpdateInventory to update inventory after user pays
        /// </summary>
        /// <returns>RedirectsToAction</returns>
        public ActionResult Paid()
        {
            ShoppingCart.UpdateInventory();

            Session.Remove(SHOPPING_CART_SESSION_OBJ);

            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Dispose method to dispose of the database object
        /// </summary>
        /// <param name="disposing"></param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JLTMEntProj/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Scrumptious Inc. </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function r(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s=u.createElement(o),i,f;for(s.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace","Ajax"];i.length;)r("track"+i.pop());return r("setAuthenticatedUserContext"),r("clearAuthenticatedUserContext"),config.disableExceptionTracking||(i="onerror",r("_"+i),f=e[i],e[i]=function(config,r,u,e,o){var s=f&&f(config,r,u,e,o);return s!==!0&&t["_"+i](config,r,u,e,o),s}),t
        }({
            instrumentationKey:"a3428046-c1cb-4ad8-9ea2-ccf26f54beee"
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Scrumptious Inc.", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Shop", "Shop", "Shopping")</li>
                    <li>@Html.ActionLink("ProductList Manager", "Index", "ManageProducts")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Scumptious Inc.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>